### ISSUE TITLE
code-loading "bootloader"

### ISSUE THREAD

**Issue by owlshrimp** [cyrozap/rv51#2]
Hi, Love what you're doing! 

I have a feature suggestion to make life easier:

Something I thought would really speed development is if you had a small state machine that (at boot) could write incoming bytes into ram/flash/eeprom. This way you could change the RISC-V firmware over serial/I2C/SPI/etc without having to reflash all the 8051 code (which can be annoying on some devices).

User-experience would be similar to the AVR bootloader, which allows you to quickly download code over a serial port instead of burning the chips with an ICSP programmer (or it times out and just jumps to the existing code).

What I don't know is what peripheral the incoming data should be searched for. I presume not all 8051s implement the same peripherals. At the same time, targeting too many interfaces is a chore and should be minimized.

**Comment by cyrozap** [comment]
While that's a really interesting idea, I won't be implementing anything like that in my version of rv51. For one thing, there's simply too many potential platforms and use cases to make supporting that feasible. For example, many 8051-based microcontrollers use the standard 8051 serial port peripheral, but some use memory-mapped 8250-style UARTs in XDATA space. And while many users might want to load code over serial, others might want to load it over SPI, I2C, or even USB or PCIe, depending on what peripherals are available on their target microcontroller and their target application. There's also the issues of what protocol would be used and the trade-off between protocol robustness and code complexity, but I won't get into those since the support issue already makes this a nonstarter for me.

All that said, I deliberately wrote rv51 to be as generic as possible in order to make it straightforward to port for use with many different 8051-based microcontrollers, so please feel free to add a bootloader to your own fork of rv51--the project license gives you the right to do so! Just keep in mind that I won't be accepting any PRs adding a bootloader for the reasons stated previously.

I'm closing this issue for now since I'm not going to add a bootloader, but I _might_ (big emphasis on "might"--I make no guarantees that I'll ever get around to doing this) at some point try adding support for executing code from XDATA space in addition to CODE/PMEM. That code could be kept fairly generic while still providing some of the requested functionality (executing RISC-V code from RAM), and would enable the development of RISC-V bootloaders as well.
