### ISSUE TITLE
Interest in the project. Guidelines needed.

### ISSUE THREAD

**Issue by djStolen** [cyrozap/rv51#3]
Hi,

I would have interest in the project, but would need some guidelines to contribute.

I saw interrupts are missing and compressed instructions.

Are you planning on implementing C differently than I or just directing to I?

Could you give some guidelines on interrupts?

Thanks

**Comment by cyrozap** [comment]
My plan for the C extension was to have the instruction fetch function check if the instruction it's reading is compressed and, if so, decompress the instruction and put the decompressed instruction in the `instruction_0..instruction_3` registers. Then the decode/execute process can run as normal.

As for interrupts, I haven't really looked into it too deeply yet, but I was thinking I'd add some ISRs whose only function would be to set flags indicating which interrupt was triggered. Then, before every instruction fetch, a function would run that would check those flags and handle any interrupts that were configured on the RISC-V side. Or something like that--again, I haven't looked into compressed instructions very deeply yet. I think the tricky part with this will be finding space to store all the Machine-mode CSRs since there's quite a few of them, and while most of them are read-only there's going to be a non-zero impact on the code size in order to handle all of those cases.

**Comment by owlshrimp** [comment]
How close are you to running out of resources on a "standard" 8051? (sram, code size, etc)

**Comment by cyrozap** [comment]
@Matthew-Bradley, as of commit f598da24d07a96ce6e541c1fce0e79b81c198ddd, rv51 uses the following resources:

- Low internal RAM (0x00-0x7F, direct/indirectly addressable memory): 101/128 bytes
  - 8 bytes of BANK0 (0x00-0x07) registers for temporary variable storage (one is currently unused in rv51, but by the conventions/guidelines I set it must remain available for use so I'm counting it as "used" here)
  - 13 bytes of BITS (0x20-0x2F) registers for the fetched RISC-V instruction and extracted instruction fields (rd, rs1, rs2, funct3, funct7, immediate)
  - 12 bytes of temporary RISC-V register storage (because when the source and destination RISC-V registers are the same, you can't operate on the values in-place)
  - 2 bytes for the calculated current/next RISC-V program counter (needed for JAL, JALR, and AUIPC, but I may be able to free up these two bytes with some optimizations since they're really only used as temporary storage)
  - 2 bytes for the saved DPTR that points to the current RISC-V instruction (needed for JAL and AUIPC because DPTR points to the next RISC-V instruction after every fetch, and I need to calculate those based on the pointer to the current RISC-V instruction)
  - 64 bytes for the stack (though that's only the space I've allocated, and by my estimates most goes unused)
- High internal RAM (0x80-0xFF, indirect addressing only): 128/128 bytes
  - 128 bytes for the 32 32-bit RISC-V registers
- Code memory: 3943/65536 bytes (architectural maximum--the actual maximum will depend on the specific 8051 implementation)
- XDATA: 0/65536 bytes (architectural maximum--the actual maximum will depend on the specific 8051 implementation)
  - I don't use XDATA because I want to make sure rv51 can be fairly easily ported to different 8051 variants, and not all 8051 variants have XRAM at the same location or any XRAM at all.
  - Not using XRAM also means the emulated RISC-V can access the full XDATA memory space without rv51 having to mask or translate access to that space.

So by my estimate, there's at least 24 bytes in BANK1, BANK2, and BANK3 that could be used for M-mode register storage, and 3 bytes in BITS that could be used for M-mode flag storage. I also might be able to free up 32 bytes or more from the space currently allocated to the stack, but am hesitant to do so until I can precisely calculate the maximum stack space rv51 uses.

As for code space, while there's still a lot of room _architecturally_, many in-the-wild implementations of the 8051 have less than 64 kB of code space in the chip. With rv51 already taking up almost a full 4096 bytes, and with code space being shared between rv51 and the RISC-V code, and considering how terrible the 8051 is with bit field extractions (especially on words larger than 8 bits), I'm a bit worried that the amount of code necessary to support the C extension might end up excluding variants of the 8051 with only 8 kB of code space from being able to run rv51. Plus, because of the decompression steps, executing compressed instructions will necessarily take more time than their uncompressed counterparts, so if the code size increase on the 8051 side and the savings on the RISC-V side cancel out, the end result will simply be that the code will run slower. And while it might be possible to solve some of these problems by making the C extension support optional, supporting an additional build configuration will significantly complicate the testing process and make maintaining the code more difficult.

**Comment by owlshrimp** [comment]
I very much appreciate the level of care you're employing on this, especially concerning the maximum stack usage.

Does supporting C bring any compatibility improvements? ie. is it mandatory that any compilers emit compressed code?

**Comment by cyrozap** [comment]
@Matthew-Bradley,

> I very much appreciate the level of care you're employing on this, especially concerning the maximum stack usage.

I'm glad you appreciate that, though I must admit I'm really only putting in this much care to help preserve my sanity. Having to debug stack overflows on the 8051 can be an absolute nightmare, especially when it's a subtle bug that causes some RISC-V instructions to get executed incorrectly. Since I work on this project for the fun of it, I try to avoid "debugging hell" as much as possible.

In non-recursive, deterministic code like this, it should be possible to statically calculate the stack size requirements based on the maximum call depth and the number of "push" instructions used. To that end, I'm thinking of writing a Ghidra plugin that can perform that kind of analysis, but I'm not sure what that would look like, yet.

Fun fact: The code I've published in this repo is actually the second iteration of this project, which I wrote from scratch after completely throwing away the first one. The first version I started writing was not as rigidly structured, so while it was slightly more optimized than this version (there was less shuffling around of data), adding support for even one RISC-V instruction quickly caused the complexity to spiral out of control, and the code became unmaintainable. So, I scrapped all that and came up with the [rules and conventions I put near the top of main.S][rules] and used [this spreadsheet][spreadsheet] to visually keep track of 8051 register allocation.

> Does supporting C bring any compatibility improvements? ie. is it mandatory that any compilers emit compressed code?

Interestingly enough, yes! One of the reasons I considered implementing it is that [the Rust compiler, rustc, only supports the following 32-bit RISC-V targets as "Tier 2"][tier-2] ("guaranteed to build", with official binary releases):

- `riscv32i-unknown-none-elf`
- `riscv32imac-unknown-none-elf`
- `riscv32imc-unknown-none-elf`

Of those three, only the I-only target does not require support for compressed instructions. This means that if you want to use a Rust compiler with Tier 2 support, and you want to build for 32-bit RISC-V and take advantage of support for multiply/divide instructions, your RISC-V implementation must also support the C extension.

While [there is Tier 3 support for `riscv32im-unknown-none-elf`][tier-3], a target that does not require support for the C extension, Tier 3 support implies that the Rust project does not automatically build or test compilers for that target, and official builds of the compiler for that target are not available.


[rules]: https://github.com/cyrozap/rv51/blob/8fa14eb7721df9e34f7545a30ab2cf262ac18790/src/main.S#L20-L35
[spreadsheet]: https://github.com/cyrozap/rv51/blob/8fa14eb7721df9e34f7545a30ab2cf262ac18790/doc/Register-Mapping.ods
[tier-2]: https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-2
[tier-3]: https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-3

**Comment by owlshrimp** [comment]
Small side question: you support the M extension, but is this backed by hardware multiply in the 8051?

**Comment by cyrozap** [comment]
@Matthew-Bradley, yes, the [MUL](https://github.com/cyrozap/rv51/blob/8fa14eb7721df9e34f7545a30ab2cf262ac18790/src/main.S#L1786-L1902) and [MULH\[\[S\]U\]](https://github.com/cyrozap/rv51/blob/8fa14eb7721df9e34f7545a30ab2cf262ac18790/src/main.S#L2191-L2449) implementations in rv51 are backed by the 8051's 8-bit multiply instruction, so it is faster than looped addition (in 8051 or emulated RISC-V code), but it's still very slow due to the number of 8051 multiply and add instructions required (10 `mul` and 14 `add[c]` instructions for the basic MUL, and 16 `mul` and 57 `add[c]` for MULH\[\[S\]U\]) and all the `mov` instructions required to set up the multiplies and move the results to where they need to go.

So, yes, the M extension is backed by the 8051's hardware multiply, but when targeting rv51 with hand-coded RISC-V assembly it's best to avoid using MUL instructions, and MULH\[\[S\]U\] instructions should be avoided except where absolutely necessary. MUL is sped up a lot by neither calculating nor saving the full 64-bit result (hence the reduced number of `mul`'s and `add[c]`'s), but that comes at the expense of requiring MULH\[\[S\]U\] to perform the full 64-bit calculation _again_ even though MUL has already calculated the lower 32 bits. I made this trade-off because I wanted to be able to fully support the M extension while accelerating the common case (MUL is much more commonly used than MULH\[\[S\]U\]). Fortunately, compilers like GCC and Clang are smart enough to know that a few shifts and adds are usually faster than a "hardware" multiply by a constant and will generally avoid using MUL instructions unless both multiplication factors are unknown at compile-time. So it's always safe to enable the M extension in your compiler when building RISC-V code for rv51--either a multiply by a constant will get optimized down to shifts and adds, or a multiply instruction will be used and will be faster than performing the same multiplication in a loop of RISC-V code.

And in case you were also wondering, [the DIV\[U\]/REM\[U\] implementation](https://github.com/cyrozap/rv51/blob/8fa14eb7721df9e34f7545a30ab2cf262ac18790/src/main.S#L2595-L2726) _does not_ use the 8051 hardware division instruction. As far as I could tell from the research I did, an algorithm incorporating an 8-bit divide instruction (which is very slow in most implementations of the 8051) would be very complicated to implement and might even require some 32-bit multiplication (and remember how slow _that_ is). So instead of implementing a complex algorithm that might be very slow, I just used SDCC's tried-and-tested 32-bit division code (with some further optimizations and wrapper code to adapt it for use in the DIV\[U\]/REM\[U\] execution functions), which is very fast and easy to reason about. Like with the MUL implementation, DIV\[U\]/REM\[U\] is faster than the equivalent algorithm implemented in RISC-V code and then emulated by rv51.

**Comment by owlshrimp** [comment]
Was absent-mindedly thinking about how one might package this as a crate, say for support of some known-compatible 8051 chips. I'm not supper familiar with packaging conventions, but I suppose you'd want a rust HAL layer written and compiled for risc-v that makes peripherals available, plus a rust 8051 assembler.

Have you looked at whether a rust 8051 assembler exists? I suppose at the very least it's a simpler thing to tackle than a full-blown compiler?

**Comment by cyrozap** [comment]
@Matthew-Bradley, packaging this code plus an 8051 assembler--as a Rust crate or otherwise--is out of scope for this project. If you'd like to do that, then by all means do so, but I'm not going to accept a PR for that. As interesting as that all sounds, in the interest of not overextending myself I'd like to keep the scope of rv51 to a minimum.

As for an 8051 assembler written in Rust, a cursory search identified a couple ([fizyk20/asm-8051-rs](https://github.com/fizyk20/asm-8051-rs), [KaKnife/asm622](https://gitlab.com/KaKnife/asm622)), but I can't speak to their stage of development or their quality. As much as I dislike ASxxxx (its paginated assembly listing output really threw me for a loop the first time I saw it, and it sometimes fails to warn when I write an instruction that assembles to something technically correct but different than I was expecting), it does what it's supposed to do and without much hassle. And having experience writing parsers and toy assemblers, I know that 99% of the work will not be spent on the fun parts (implementing instructions) but on the really, _really_, boring parts like error handling and addressing nonsense (`sjmp` can't jump more than -128/+127 bytes, `ajmp` can only jump within a 2KB block, etc.), so while writing an 8051 assembler in Rust would be much easier than writing a Rust compiler backend, it's still a non-trivial amount of work.

**Comment by owlshrimp** [comment]
> As interesting as that all sounds, in the interest of not overextending myself I'd like to keep the scope of rv51 to a minimum.
Fair enough.

It was more a theoretical question, since I expect there'd be resistance to an opaque bin file. An assembler written in rust which could be compiled and then passed the assembly seems like the next best thing.

What assembler are you currently using?

>...I know that 99% of the work will not be spent on the fun parts (implementing instructions) but on the really, _really_, boring parts like error handling and addressing nonsense (`sjmp` can't jump more than -128/+127 bytes, `ajmp` can only jump within a 2KB block, etc.)...

Do you know a good 8051 reference where these many small details can be found?

**Comment by cyrozap** [comment]
@Matthew-Bradley

> What assembler are you currently using?

[The modified version of ASxxxx that comes with SDCC](https://github.com/cyrozap/rv51/blob/1f178a1ff64290e3ac6a89b1375847584b970a17/src/Makefile#L19).

> Do you know a good 8051 reference where these many small details can be found?

The [1994 Intel MCS® 51 Microcontroller Family User's Manual](https://web.archive.org/web/20220703014723if_/http://datasheets.chipdb.org/Intel/MCS51/MANUALS/27238302.PDF) is a good reference. The instruction set information starts on page 51, and includes information on the address operands and which instructions use them:

> addr16 - 16-bit destination address. Used by LCALL & LJMP. A branch can be anywhere within the 64K-byte Program Memory address space.
> addr11 - 11-bit destination address. Used by ACALL & AJMP. The branch will be within the same 2K-byte page of program memory as the first byte of the following instruction.
> rel - Signed (two’s complement) 8-bit offset byte. Used by SJMP and all conditional jumps. Range is -128 to +127 bytes relative to first byte of the following instruction.

**Comment by cyrozap** [comment]
I've added a [contribution guide](https://github.com/cyrozap/rv51/blob/master/CONTRIBUTING.md) that includes information on what features are in-scope for this project, what features are out-of-scope, and suggestions on how to implement some of the in-scope features. With this, I'm going to close this issue, but please feel free to open another one if you feel the contribution guide is missing anything.

**Comment by chaoyangnz** [comment]
Thanks for the great work, recently I fall into the similar difficulty to compile Zig to 8051. 

Your discussion and implementation internals are worth a documentation
