### ISSUE TITLE
Implement mcycle CSR?

### ISSUE THREAD

**Issue by jefftrull** [cyrozap/rv51#4]
I have made an implementation for my own purposes (based on timer 2 plus an external count) that seems to work, and if this is of interest I can create a PR.

**Comment by cyrozap** [comment]
Sorry to get back to you so late on this. I'm not interested in including emulation of the mcycle CSR in rv51, but I do appreciate you publishing your implementation.

A while ago, I considered implementing this CSR myself in essentially the same manner, but ultimately decided against it. I had the following reasons for doing so:

1. Timer 2 is not present on all 8051 implementations (even if an implementation has 256 bytes of IRAM, there's no guarantee that Timer 2 is present or functional). To ease the maintenance burden, I try not to use any 8051 features and peripherals that I don't absolutely need or that might not be present in all implementations (and I am aware of real implementations that don't have Timer 2 but do otherwise support rv51).
2. Using an ISR to set the upper bits introduces a number of potential issues. For instance, if the RISC-V code uses SFR writes to disable interrupts, mcycle might not be updated when it needs to be, and this could cause weird, hard to debug issues in the RISC-V code. This could be fixed with better isolation between the 8051 hardware and the RISC-V code, but rv51's support for passing interrupts up to the RISC-V code is still very immature and I haven't yet figured out how I want to design the virtual interrupt controller. And besides that, interrupts are inherently non-deterministic and I just don't feel comfortable implementing what's supposed to be a very deterministic feature with a feature that is not deterministic.

Essentially, I don't have enough confidence in the underlying 8051 features that are needed to back the RISC-V feature for me to add it to rv51. And having that confidence is essential to avoid a maintenance nightmare.

**Comment by jefftrull** [comment]
Fine by me! I really appreciate rv51 and I intend to always offer my improvements upstream. You can expect more going forward :)

rv51 has proven helpful in porting TinyUSB to an 8051-based system. It is too large when compiled unmodified by sdcc, but as an emulator + RISCV binary it has plenty of room. Hopefully I can do a performance comparison.
